from rosie.log import logger
print("------")
logger.debug("debug message")
print("------")
logger.warning("warning message")
logger.info("Here we go!!! vvvvvvvvvvvvvvvvvvvvvvvv")
print("------")
logger.critical("Here we go!!!")
print("------")
print("Hello, world!")
